package com.yougou.itemcenter.domain.example;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CategoryExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table itemcenter_category
     *
     * @mbggenerated Sat Jun 04 09:59:40 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table itemcenter_category
     *
     * @mbggenerated Sat Jun 04 09:59:40 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table itemcenter_category
     *
     * @mbggenerated Sat Jun 04 09:59:40 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table itemcenter_category
     *
     * @mbggenerated Sat Jun 04 09:59:40 CST 2016
     */
    protected Integer limitStart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table itemcenter_category
     *
     * @mbggenerated Sat Jun 04 09:59:40 CST 2016
     */
    protected Integer limitEnd;

    public CategoryExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    public String getOrderByClause() {
        return orderByClause;
    }

    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    public boolean isDistinct() {
        return distinct;
    }

    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    public CategoryExample(Integer limitStart, Integer limitEnd) {
        oredCriteria = new ArrayList<Criteria>();
        this.limitStart=limitStart;
        this.limitEnd=limitEnd;
    }

    public void setLimitStart(Integer limitStart) {
        this.limitStart=limitStart;
    }

    public Integer getLimitStart() {
        return limitStart;
    }

    public void setLimitEnd(Integer limitEnd) {
        this.limitEnd=limitEnd;
    }

    public Integer getLimitEnd() {
        return limitEnd;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table itemcenter_category
     *
     * @mbggenerated Sat Jun 04 09:59:40 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andLevelIsNull() {
            addCriterion("level is null");
            return (Criteria) this;
        }

        public Criteria andLevelIsNotNull() {
            addCriterion("level is not null");
            return (Criteria) this;
        }

        public Criteria andLevelEqualTo(Integer value) {
            addCriterion("level =", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelNotEqualTo(Integer value) {
            addCriterion("level <>", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelGreaterThan(Integer value) {
            addCriterion("level >", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelGreaterThanOrEqualTo(Integer value) {
            addCriterion("level >=", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelLessThan(Integer value) {
            addCriterion("level <", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelLessThanOrEqualTo(Integer value) {
            addCriterion("level <=", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelIn(List<Integer> values) {
            addCriterion("level in", values, "level");
            return (Criteria) this;
        }

        public Criteria andLevelNotIn(List<Integer> values) {
            addCriterion("level not in", values, "level");
            return (Criteria) this;
        }

        public Criteria andLevelBetween(Integer value1, Integer value2) {
            addCriterion("level between", value1, value2, "level");
            return (Criteria) this;
        }

        public Criteria andLevelNotBetween(Integer value1, Integer value2) {
            addCriterion("level not between", value1, value2, "level");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andProductparameterIsNull() {
            addCriterion("productParameter is null");
            return (Criteria) this;
        }

        public Criteria andProductparameterIsNotNull() {
            addCriterion("productParameter is not null");
            return (Criteria) this;
        }

        public Criteria andProductparameterEqualTo(String value) {
            addCriterion("productParameter =", value, "productparameter");
            return (Criteria) this;
        }

        public Criteria andProductparameterNotEqualTo(String value) {
            addCriterion("productParameter <>", value, "productparameter");
            return (Criteria) this;
        }

        public Criteria andProductparameterGreaterThan(String value) {
            addCriterion("productParameter >", value, "productparameter");
            return (Criteria) this;
        }

        public Criteria andProductparameterGreaterThanOrEqualTo(String value) {
            addCriterion("productParameter >=", value, "productparameter");
            return (Criteria) this;
        }

        public Criteria andProductparameterLessThan(String value) {
            addCriterion("productParameter <", value, "productparameter");
            return (Criteria) this;
        }

        public Criteria andProductparameterLessThanOrEqualTo(String value) {
            addCriterion("productParameter <=", value, "productparameter");
            return (Criteria) this;
        }

        public Criteria andProductparameterLike(String value) {
            addCriterion("productParameter like", value, "productparameter");
            return (Criteria) this;
        }

        public Criteria andProductparameterNotLike(String value) {
            addCriterion("productParameter not like", value, "productparameter");
            return (Criteria) this;
        }

        public Criteria andProductparameterIn(List<String> values) {
            addCriterion("productParameter in", values, "productparameter");
            return (Criteria) this;
        }

        public Criteria andProductparameterNotIn(List<String> values) {
            addCriterion("productParameter not in", values, "productparameter");
            return (Criteria) this;
        }

        public Criteria andProductparameterBetween(String value1, String value2) {
            addCriterion("productParameter between", value1, value2, "productparameter");
            return (Criteria) this;
        }

        public Criteria andProductparameterNotBetween(String value1, String value2) {
            addCriterion("productParameter not between", value1, value2, "productparameter");
            return (Criteria) this;
        }

        public Criteria andSaleparameterIsNull() {
            addCriterion("saleParameter is null");
            return (Criteria) this;
        }

        public Criteria andSaleparameterIsNotNull() {
            addCriterion("saleParameter is not null");
            return (Criteria) this;
        }

        public Criteria andSaleparameterEqualTo(String value) {
            addCriterion("saleParameter =", value, "saleparameter");
            return (Criteria) this;
        }

        public Criteria andSaleparameterNotEqualTo(String value) {
            addCriterion("saleParameter <>", value, "saleparameter");
            return (Criteria) this;
        }

        public Criteria andSaleparameterGreaterThan(String value) {
            addCriterion("saleParameter >", value, "saleparameter");
            return (Criteria) this;
        }

        public Criteria andSaleparameterGreaterThanOrEqualTo(String value) {
            addCriterion("saleParameter >=", value, "saleparameter");
            return (Criteria) this;
        }

        public Criteria andSaleparameterLessThan(String value) {
            addCriterion("saleParameter <", value, "saleparameter");
            return (Criteria) this;
        }

        public Criteria andSaleparameterLessThanOrEqualTo(String value) {
            addCriterion("saleParameter <=", value, "saleparameter");
            return (Criteria) this;
        }

        public Criteria andSaleparameterLike(String value) {
            addCriterion("saleParameter like", value, "saleparameter");
            return (Criteria) this;
        }

        public Criteria andSaleparameterNotLike(String value) {
            addCriterion("saleParameter not like", value, "saleparameter");
            return (Criteria) this;
        }

        public Criteria andSaleparameterIn(List<String> values) {
            addCriterion("saleParameter in", values, "saleparameter");
            return (Criteria) this;
        }

        public Criteria andSaleparameterNotIn(List<String> values) {
            addCriterion("saleParameter not in", values, "saleparameter");
            return (Criteria) this;
        }

        public Criteria andSaleparameterBetween(String value1, String value2) {
            addCriterion("saleParameter between", value1, value2, "saleparameter");
            return (Criteria) this;
        }

        public Criteria andSaleparameterNotBetween(String value1, String value2) {
            addCriterion("saleParameter not between", value1, value2, "saleparameter");
            return (Criteria) this;
        }

        public Criteria andShowindexIsNull() {
            addCriterion("showIndex is null");
            return (Criteria) this;
        }

        public Criteria andShowindexIsNotNull() {
            addCriterion("showIndex is not null");
            return (Criteria) this;
        }

        public Criteria andShowindexEqualTo(Integer value) {
            addCriterion("showIndex =", value, "showindex");
            return (Criteria) this;
        }

        public Criteria andShowindexNotEqualTo(Integer value) {
            addCriterion("showIndex <>", value, "showindex");
            return (Criteria) this;
        }

        public Criteria andShowindexGreaterThan(Integer value) {
            addCriterion("showIndex >", value, "showindex");
            return (Criteria) this;
        }

        public Criteria andShowindexGreaterThanOrEqualTo(Integer value) {
            addCriterion("showIndex >=", value, "showindex");
            return (Criteria) this;
        }

        public Criteria andShowindexLessThan(Integer value) {
            addCriterion("showIndex <", value, "showindex");
            return (Criteria) this;
        }

        public Criteria andShowindexLessThanOrEqualTo(Integer value) {
            addCriterion("showIndex <=", value, "showindex");
            return (Criteria) this;
        }

        public Criteria andShowindexIn(List<Integer> values) {
            addCriterion("showIndex in", values, "showindex");
            return (Criteria) this;
        }

        public Criteria andShowindexNotIn(List<Integer> values) {
            addCriterion("showIndex not in", values, "showindex");
            return (Criteria) this;
        }

        public Criteria andShowindexBetween(Integer value1, Integer value2) {
            addCriterion("showIndex between", value1, value2, "showindex");
            return (Criteria) this;
        }

        public Criteria andShowindexNotBetween(Integer value1, Integer value2) {
            addCriterion("showIndex not between", value1, value2, "showindex");
            return (Criteria) this;
        }

        public Criteria andSupercategoryidIsNull() {
            addCriterion("superCategoryId is null");
            return (Criteria) this;
        }

        public Criteria andSupercategoryidIsNotNull() {
            addCriterion("superCategoryId is not null");
            return (Criteria) this;
        }

        public Criteria andSupercategoryidEqualTo(Long value) {
            addCriterion("superCategoryId =", value, "supercategoryid");
            return (Criteria) this;
        }

        public Criteria andSupercategoryidNotEqualTo(Long value) {
            addCriterion("superCategoryId <>", value, "supercategoryid");
            return (Criteria) this;
        }

        public Criteria andSupercategoryidGreaterThan(Long value) {
            addCriterion("superCategoryId >", value, "supercategoryid");
            return (Criteria) this;
        }

        public Criteria andSupercategoryidGreaterThanOrEqualTo(Long value) {
            addCriterion("superCategoryId >=", value, "supercategoryid");
            return (Criteria) this;
        }

        public Criteria andSupercategoryidLessThan(Long value) {
            addCriterion("superCategoryId <", value, "supercategoryid");
            return (Criteria) this;
        }

        public Criteria andSupercategoryidLessThanOrEqualTo(Long value) {
            addCriterion("superCategoryId <=", value, "supercategoryid");
            return (Criteria) this;
        }

        public Criteria andSupercategoryidIn(List<Long> values) {
            addCriterion("superCategoryId in", values, "supercategoryid");
            return (Criteria) this;
        }

        public Criteria andSupercategoryidNotIn(List<Long> values) {
            addCriterion("superCategoryId not in", values, "supercategoryid");
            return (Criteria) this;
        }

        public Criteria andSupercategoryidBetween(Long value1, Long value2) {
            addCriterion("superCategoryId between", value1, value2, "supercategoryid");
            return (Criteria) this;
        }

        public Criteria andSupercategoryidNotBetween(Long value1, Long value2) {
            addCriterion("superCategoryId not between", value1, value2, "supercategoryid");
            return (Criteria) this;
        }

        public Criteria andIsdeleteIsNull() {
            addCriterion("isDelete is null");
            return (Criteria) this;
        }

        public Criteria andIsdeleteIsNotNull() {
            addCriterion("isDelete is not null");
            return (Criteria) this;
        }

        public Criteria andIsdeleteEqualTo(Byte value) {
            addCriterion("isDelete =", value, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteNotEqualTo(Byte value) {
            addCriterion("isDelete <>", value, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteGreaterThan(Byte value) {
            addCriterion("isDelete >", value, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteGreaterThanOrEqualTo(Byte value) {
            addCriterion("isDelete >=", value, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteLessThan(Byte value) {
            addCriterion("isDelete <", value, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteLessThanOrEqualTo(Byte value) {
            addCriterion("isDelete <=", value, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteIn(List<Byte> values) {
            addCriterion("isDelete in", values, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteNotIn(List<Byte> values) {
            addCriterion("isDelete not in", values, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteBetween(Byte value1, Byte value2) {
            addCriterion("isDelete between", value1, value2, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteNotBetween(Byte value1, Byte value2) {
            addCriterion("isDelete not between", value1, value2, "isdelete");
            return (Criteria) this;
        }

        public Criteria andGmtmodifiedIsNull() {
            addCriterion("gmtModified is null");
            return (Criteria) this;
        }

        public Criteria andGmtmodifiedIsNotNull() {
            addCriterion("gmtModified is not null");
            return (Criteria) this;
        }

        public Criteria andGmtmodifiedEqualTo(Date value) {
            addCriterion("gmtModified =", value, "gmtmodified");
            return (Criteria) this;
        }

        public Criteria andGmtmodifiedNotEqualTo(Date value) {
            addCriterion("gmtModified <>", value, "gmtmodified");
            return (Criteria) this;
        }

        public Criteria andGmtmodifiedGreaterThan(Date value) {
            addCriterion("gmtModified >", value, "gmtmodified");
            return (Criteria) this;
        }

        public Criteria andGmtmodifiedGreaterThanOrEqualTo(Date value) {
            addCriterion("gmtModified >=", value, "gmtmodified");
            return (Criteria) this;
        }

        public Criteria andGmtmodifiedLessThan(Date value) {
            addCriterion("gmtModified <", value, "gmtmodified");
            return (Criteria) this;
        }

        public Criteria andGmtmodifiedLessThanOrEqualTo(Date value) {
            addCriterion("gmtModified <=", value, "gmtmodified");
            return (Criteria) this;
        }

        public Criteria andGmtmodifiedIn(List<Date> values) {
            addCriterion("gmtModified in", values, "gmtmodified");
            return (Criteria) this;
        }

        public Criteria andGmtmodifiedNotIn(List<Date> values) {
            addCriterion("gmtModified not in", values, "gmtmodified");
            return (Criteria) this;
        }

        public Criteria andGmtmodifiedBetween(Date value1, Date value2) {
            addCriterion("gmtModified between", value1, value2, "gmtmodified");
            return (Criteria) this;
        }

        public Criteria andGmtmodifiedNotBetween(Date value1, Date value2) {
            addCriterion("gmtModified not between", value1, value2, "gmtmodified");
            return (Criteria) this;
        }

        public Criteria andGmtcreateIsNull() {
            addCriterion("gmtCreate is null");
            return (Criteria) this;
        }

        public Criteria andGmtcreateIsNotNull() {
            addCriterion("gmtCreate is not null");
            return (Criteria) this;
        }

        public Criteria andGmtcreateEqualTo(Date value) {
            addCriterion("gmtCreate =", value, "gmtcreate");
            return (Criteria) this;
        }

        public Criteria andGmtcreateNotEqualTo(Date value) {
            addCriterion("gmtCreate <>", value, "gmtcreate");
            return (Criteria) this;
        }

        public Criteria andGmtcreateGreaterThan(Date value) {
            addCriterion("gmtCreate >", value, "gmtcreate");
            return (Criteria) this;
        }

        public Criteria andGmtcreateGreaterThanOrEqualTo(Date value) {
            addCriterion("gmtCreate >=", value, "gmtcreate");
            return (Criteria) this;
        }

        public Criteria andGmtcreateLessThan(Date value) {
            addCriterion("gmtCreate <", value, "gmtcreate");
            return (Criteria) this;
        }

        public Criteria andGmtcreateLessThanOrEqualTo(Date value) {
            addCriterion("gmtCreate <=", value, "gmtcreate");
            return (Criteria) this;
        }

        public Criteria andGmtcreateIn(List<Date> values) {
            addCriterion("gmtCreate in", values, "gmtcreate");
            return (Criteria) this;
        }

        public Criteria andGmtcreateNotIn(List<Date> values) {
            addCriterion("gmtCreate not in", values, "gmtcreate");
            return (Criteria) this;
        }

        public Criteria andGmtcreateBetween(Date value1, Date value2) {
            addCriterion("gmtCreate between", value1, value2, "gmtcreate");
            return (Criteria) this;
        }

        public Criteria andGmtcreateNotBetween(Date value1, Date value2) {
            addCriterion("gmtCreate not between", value1, value2, "gmtcreate");
            return (Criteria) this;
        }

        public Criteria andFeatureIsNull() {
            addCriterion("feature is null");
            return (Criteria) this;
        }

        public Criteria andFeatureIsNotNull() {
            addCriterion("feature is not null");
            return (Criteria) this;
        }

        public Criteria andFeatureEqualTo(String value) {
            addCriterion("feature =", value, "feature");
            return (Criteria) this;
        }

        public Criteria andFeatureNotEqualTo(String value) {
            addCriterion("feature <>", value, "feature");
            return (Criteria) this;
        }

        public Criteria andFeatureGreaterThan(String value) {
            addCriterion("feature >", value, "feature");
            return (Criteria) this;
        }

        public Criteria andFeatureGreaterThanOrEqualTo(String value) {
            addCriterion("feature >=", value, "feature");
            return (Criteria) this;
        }

        public Criteria andFeatureLessThan(String value) {
            addCriterion("feature <", value, "feature");
            return (Criteria) this;
        }

        public Criteria andFeatureLessThanOrEqualTo(String value) {
            addCriterion("feature <=", value, "feature");
            return (Criteria) this;
        }

        public Criteria andFeatureLike(String value) {
            addCriterion("feature like", value, "feature");
            return (Criteria) this;
        }

        public Criteria andFeatureNotLike(String value) {
            addCriterion("feature not like", value, "feature");
            return (Criteria) this;
        }

        public Criteria andFeatureIn(List<String> values) {
            addCriterion("feature in", values, "feature");
            return (Criteria) this;
        }

        public Criteria andFeatureNotIn(List<String> values) {
            addCriterion("feature not in", values, "feature");
            return (Criteria) this;
        }

        public Criteria andFeatureBetween(String value1, String value2) {
            addCriterion("feature between", value1, value2, "feature");
            return (Criteria) this;
        }

        public Criteria andFeatureNotBetween(String value1, String value2) {
            addCriterion("feature not between", value1, value2, "feature");
            return (Criteria) this;
        }
    }

    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table itemcenter_category
     *
     * @mbggenerated Sat Jun 04 09:59:40 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}